export enum DL8VideoFormatEnum {
  STEREO_180_LR = "STEREO_180_LR",
  STEREO_180_LR_SPHERICAL = "STEREO_180_LR_SPHERICAL",
  STEREO_180_TB = "STEREO_180_TB",
  STEREO_180_TB_SPHERICAL = "STEREO_180_TB_SPHERICAL",
  STEREO_360_TB = "STEREO_360_TB",
  STEREO_360_LR = "STEREO_360_LR",
  MONO_360 = "MONO_360",
  MONO_FLAT = "MONO_FLAT",
  STEREO_FLAT_LR = "STEREO_FLAT_LR",
  STEREO_FLAT_LR_SQUARE = "STEREO_FLAT_LR_SQUARE",
  STEREO_FLAT_TB = "STEREO_FLAT_TB",
  STEREO_FLAT_TB_SQUARE = "STEREO_FLAT_TB_SQUARE",
}

export enum GoogleReCaptchaActionEnum {
  CREATE_CONTACT_SUBMIT = "CREATE_CONTACT_SUBMIT",
  SIGN_IN_SUBMIT = "SIGN_IN_SUBMIT",
}
